/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Renderer: typeof import('./src/components/Renderer.vue')['default']
    ThemeDropdown: typeof import('./src/components/ThemeDropdown.vue')['default']
  }
}
